### ISSUE TITLE
SSL: SSLV3_ALERT_BAD_CERTIFICATE 

### ISSUE THREAD

**Issue by molinto** [VaradLanke/https-file-server-python#4]
ss@l7b29r72:~/Downloads/serve/https-file-server-python$ python3.7 fileServer.py 
Can't load /home/ss/.rnd into RNG
139901109924288:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/ss/.rnd
Generating a RSA private key
.........................++++
.........................................................................................................................................++++
writing new private key to '/home/ss/Downloads/serve/https-file-server-python/key.pem'
-----
<<<<Certificate Generated>>>>>>
File Server started at https://localhost:8000
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40056)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:2570)

**Comment by VaradLanke** [comment]
Probable Solutions: 
1. Please Try to update the Python version to latest one
2. on terminal/bash try following openssl command : 
`openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes -out cert.pem -keyout key.pem`
3. Try to Generate certificate by [this](https://github.com/FiloSottile/mkcert) method : [FiloSottile](https://github.com/FiloSottile/mkcert)
